<?php
namespace grozzzny\editable;

use Yii;
use yii\easyii2\components\FastModule;

class Module extends FastModule
{
    public $settings = [
        'modelEditable' => '\grozzzny\editable\models\Editable',
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        self::registerTranslation();
    }

    public static function registerTranslation()
    {
        Yii::$app->i18n->translations['app/editable'] = [
            'class' => 'yii\i18n\PhpMessageSource',
            'sourceLanguage' => 'en-US',
            'basePath' => '@grozzzny/editable/messages',
            'fileMap' => [
                'app/editable' => 'editable.php',
            ],
        ];
    }

    public function getTitle()
    {
        // TODO: Implement getTitle() method.
        return Yii::t('app/editable', 'Editable');
    }

    public function getName()
    {
        // TODO: Implement getName() method.
        return $this->id;
    }

    public function getIcon()
    {
        // TODO: Implement getIcon() method.
        return 'file';
    }
}